version: "3.9"

services:
  api:
    build:
      context: ../..
      dockerfile: infra/docker/api.Dockerfile
    env_file:
      - ./env/api.env
    environment:
      - DB_URL=${DB_URL:-sqlite:///./dev.db}
    ports:
      - "8000:8000"
    networks:
      - app

  web:
    build:
      context: ../..
      dockerfile: infra/docker/web.Dockerfile
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:8000}
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - app

  caddy:
    image: caddy:2.8.4
    volumes:
      - ../caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
      - web
    networks:
      - app

networks:
  app: {}

volumes:
  caddy_data: {}
  caddy_config: {}
